#include "ClockNamedays.h"

#include <stddef.h>

// [měsíc][den], 1-indexováno; prázdné dny jsou nullptr.
static const char *const NAMEDAYS[13][32] = {
  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
  {0, 0, "KARINA", "RADMILA, RADOMIL", "DIANA", "DALIMIL", "KAŠPAR, MELICHAR, BALTAZAR", "VILMA", "ČESTMÍR", "VLADAN, VALTR", "BŘETISLAV", "BOHDANA", "PRAVOSLAV", "EDITA", "RADOVAN", "ALICE", "CTIRAD", "DRAHOSLAV", "VLADISLAV, VLADISLAVA", "DOUBRAVKA", "ILONA, SEBASTIÁN", "BĚLA", "SLAVOMÍR, SLAVOMÍRA", "ZDENĚK", "MILENA", "MILOŠ", "ZORA", "INGRID", "OTÝLIE", "ZDISLAVA", "ROBIN, ERNA", "MARIKA, SPYTIHNĚV"},
  {0, "HYNEK", "NELA, HROMNICE", "BLAŽEJ", "JARMILA", "DOBROMILA", "VANDA", "VERONIKA", "MILADA", "APOLENA", "MOJMÍR", "BOŽENA", "SLAVĚNA, SLÁVKA", "VĚNCESLAV, VĚNCESLAVA", "VALENTÝN, VALENTÝNA", "JIŘINA", "LJUBA", "MILOSLAVA", "GIZELA", "PATRIK", "OLDŘICH", "LENKA, ELEONORA", "PETR", "SVATOPLUK", "MATĚJ, MATYÁŠ", "LILIANA", "DOROTA", "ALEXANDR", "LUMÍR", "HORYMÍR", 0, 0},
  {0, "BEDŘICH, BEDŘIŠKA", "ANEŽKA", "KAMIL, KUNHUTA", "STELA", "KAZIMÍR", "MIROSLAV", "TOMÁŠ", "GABRIELA, ZOLTÁN", "FRANTIŠKA", "VIKTORIE", "ANDĚLA", "ŘEHOŘ", "RŮŽENA", "RÚT, MATYLDA", "IDA", "ELENA, HERBERT", "VLASTIMIL, VLASTIMILA", "EDUARD", "JOSEF, JOSEFA", "SVĚTLANA", "RADEK", "LEONA, LEONTINA, LEA", "IVONA", "GABRIEL", "MARIÁN", "EMANUEL", "DITA", "SOŇA", "TAŤÁNA", "ARNOŠT, ERNEST", "KVIDO"},
  {0, "HUGO", "ERIKA", "RICHARD", "IVANA", "MIROSLAVA, MIRKA", "VENDULA, VENUŠE", "HEŘMAN, HERMÍNA", "EMA", "DUŠAN", "DARJA", "IZABELA", "JULIUS", "ALEŠ", "VINCENC", "ANASTÁZIE", "IRENA, BERNADETA", "RUDOLF", "VALÉRIE", "ROSTISLAV", "MARCELA", "ALEXANDRA", "EVŽENIE", "VOJTĚCH", "JIŘÍ", "MAREK", "OTO", "JAROSLAV", "VLASTISLAV", "ROBERT", "BLAHOSLAV", 0},
  {0, 0, "ZIKMUND", "ALEXEJ, ALEX", "KVĚTOSLAV", "KLAUDIE", "RADOSLAV", "STANISLAV", 0, "CTIBOR", "BLAŽENA", "SVATAVA", "PANKRÁC", "SERVÁC", "BONIFÁC", "ŽOFIE, SOFIE", "PŘEMYSL", "ANETA", "NATAŠA", "IVO", "ZBYŠEK", "MONIKA", "EMIL", "VLADIMÍR, VLADIMÍRA", "JANA, VANESA", "VIOLA", "FILIP", "VALDEMAR", "VILÉM", "MAXMILIÁN, MAXIM", "FERDINAND", "KAMILA"},
  {0, "LAURA", "JARMIL", "TAMARA, KEVIN", "DALIBOR", "DOBROSLAV, DOBROSLAVA", "NORBERT", "IVETA, SLAVOJ", "MEDARD", "STANISLAVA", "GITA, MARGITA", "BRUNO", "ANTONIE", "ANTONÍN", "ROLAND, HERTA", "VÍT", "ZBYNĚK", "ADOLF", "MILAN, MILANA", "LEOŠ, LEO", "KVĚTA, KVĚTUŠE", "ALOIS, ALOISIE", "PAVLA", "ZDEŇKA", "JAN", "IVAN", "ADRIANA, ADRIAN", "LADISLAV, LADISLAVA", "LUBOMÍR", "PETR, PAVEL", "ŠÁRKA", 0},
  {0, "JAROSLAVA", "PATRICIE", "RADOMÍR, RADOMÍRA", "PROKOP", "CYRIL, METODĚJ", 0, "BOHUSLAVA", "NORA", "DRAHOSLAVA, DRAHUŠE", "LIBUŠE, AMÁLIE", "OLGA, HELGA", "BOŘEK", "MARKÉTA", "KAROLÍNA", "JINDŘICH", "LUBOŠ", "MARTINA", "DRAHOMÍRA, DRAHOMÍR", "ČENĚK", "ILJA", "VÍTĚZSLAV, VÍTĚZSLAVA", "MAGDALÉNA, MAGDA", "LIBOR", "KRISTÝNA", "JAKUB", "ANNA, ANITA", "VĚROSLAV", "VIKTOR, ALINA", "MARTA", "BOŘIVOJ", "IGNÁC"},
  {0, "OSKAR", "GUSTAV", "MILUŠE", "DOMINIK, DOMINIKA", "KRISTIÁN", "OLDŘIŠKA", "LADA", "SOBĚSLAV", "ROMAN", "VAVŘINEC", "ZUZANA", "KLÁRA", "ALENA", "ALAN", "HANA", "JÁCHYM", "PETRA", "HELENA, JELENA", "LUDVÍK", "BERNARD", "JOHANA", "BOHUSLAV", "SANDRA", "BARTOLOMĚJ", "RADIM", "LUDĚK", "OTAKAR", "AUGUSTÝN", "EVELÍNA", "VLADĚNA", "PAVLÍNA"},
  {0, "LINDA, SAMUEL", "ADÉLA", "BRONISLAV, BRONISLAVA", "JINDŘIŠKA, ROZÁLIE", "BORIS", "BOLESLAV", "REGÍNA", "MARIANA", "DANIELA", "IRMA", "DENISA, DENIS", "MARIE", "LUBOR", "RADKA", "JOLANA", "LUDMILA, LIDMILA", "NADĚŽDA, NAĎA", "KRYŠTOF", "ZITA", "OLEG", "MATOUŠ", "DARINA", "BERTA", "JAROMÍR, JAROMÍRA", "ZLATA, ZLATUŠE", "ANDREA", "JONÁŠ", "VÁCLAV, VÁCLAVA", "MICHAL, MICHAEL", "JERONÝM, RÁCHEL", 0},
  {0, "IGOR", "OLÍVIE, OLIVER", "BOHUMIL", "FRANTIŠEK", "ELIŠKA", "HANUŠ", "JUSTÝNA", "VĚRA", "ŠTEFAN, SÁRA", "MARINA", "ANDREJ", "MARCEL", "RENÁTA", "AGÁTA", "TEREZA, TEREZIE", "HAVEL, GALINA", "HEDVIKA", "LUKÁŠ", "MICHAELA, MICHALA", "VENDELÍN", "BRIGITA", "SABINA", "TEODOR", "NINA", "BEÁTA", "ERIK", "ŠARLOTA, ZOE", "JIDÁŠ, ALFRÉD", "SILVIE, SYLVA", "TADEÁŠ", "ŠTĚPÁNKA"},
  {0, "FELIX", "TOBIÁŠ", "HUBERT", "KAREL, KARLA", "MIRIAM", "LIBĚNA, LEONARD", "SASKIE", "BOHUMÍR, BOHUMÍRA", "BOHDAN", "EVŽEN", "MARTIN", "BENEDIKT", "TIBOR", "SÁVA", "LEOPOLD", "OTMAR", "MAHULENA, GERTRUDA", "ROMANA", "ALŽBĚTA", "NIKOLA", "ALBERT", "CECÍLIE", "KLEMENT", "EMÍLIE", "KATEŘINA", "ARTUR", "XENIE", "RENÉ", "ZINA", "ONDŘEJ", 0},
  {0, "IVA", "BLANKA", "SVATOSLAV", "BARBORA", "JITKA", "MIKULÁŠ", "AMBROŽ, BENJAMÍN", "KVĚTOSLAVA", "VRATISLAV", "JULIE", "DANA, DANUŠE", "SIMONA", "LUCIE", "LÝDIE", "RADANA, RADAN", "ALBÍNA", "DANIEL", "MILOSLAV", "ESTER", "DAGMAR", "NATÁLIE", "ŠIMON", "VLASTA", "ADAM, EVA", 0, "ŠTĚPÁN", "ŽANETA", "BOHUMILA", "JUDITA", "DAVID", "SILVESTR"},
};

const char *czechNamedayFor(int month, int day) {
  if (month < 1 || month > 12 || day < 1 || day > 31) return NULL;
  return NAMEDAYS[month][day];
}
