#pragma once

#include <Arduino.h>

const char DIAGNOSTIC_PAGE[] PROGMEM = R"HTML(<!doctype html>
<html lang="cs">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Waveshare Hodiny – diagnostika</title>
  <style>
    :root{color-scheme:dark;--bg:#0d1215;--panel:#171e22;--line:#344047;--text:#f3f6f7;--muted:#98a5ac;--cyan:#4ccbec;--green:#65c744;--red:#ff6262;--radius:12px}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.45 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{width:min(100% - 32px,1240px);margin:auto;padding:48px 0 64px}header{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:32px}h1{font-size:32px;margin:0 0 7px}.subtitle{color:var(--muted)}.state{display:inline-flex;align-items:center;gap:8px;color:var(--green);font-weight:700}.state::before{content:"";width:9px;height:9px;border-radius:50%;background:currentColor}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.card{min-width:0;padding:20px;border:1px solid var(--line);border-radius:var(--radius);background:var(--panel)}.card.wide{grid-column:span 4}.card h2{margin:0 0 16px;font-size:18px}.values{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:9px 18px}.label{color:var(--muted)}.value{text-align:right;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.ok{color:var(--green)}.error{color:var(--red)}.notice{margin-top:24px;padding:16px 18px;border:1px solid #315765;border-radius:var(--radius);background:#102129;color:#b9eafa}.footer{margin-top:20px;color:var(--muted);font-size:13px}.pulse{color:var(--cyan)}@media(max-width:1000px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.card.wide{grid-column:span 2}}@media(max-width:760px){main{padding:28px 0 44px}.grid{grid-template-columns:1fr}.card,.card.wide{grid-column:1}header{display:block}h1{font-size:28px}.state{margin-top:12px}}
    .warn{color:var(--red)}
  </style>
</head>
<body>
<main>
  <header><div><h1>Waveshare Hodiny</h1><div class="subtitle">Diagnostika zařízení pouze pro čtení</div></div><div class="state" id="connectionState">Zařízení je připojeno</div></header>
  <div class="grid">
    <section class="card"><h2>Firmware</h2><div class="values"><span class="label">Verze</span><span class="value" id="firmwareVersion">—</span><span class="label">Stav aktualizace</span><span class="value" id="firmwareState">—</span><span class="label">Uptime</span><span class="value" id="uptime">—</span><span class="label">Poslední restart</span><span class="value" id="resetReason">—</span></div></section>
    <section class="card"><h2>Hardware</h2><div class="values"><span class="label">Čip</span><span class="value" id="chip">—</span><span class="label">CPU</span><span class="value" id="cpu">—</span><span class="label">Frekvence displeje</span><span class="value" id="displayClock">—</span><span class="label">Flash</span><span class="value" id="flash">—</span><span class="label">PSRAM</span><span class="value" id="psram">—</span></div></section>
    <section class="card"><h2>Síť</h2><div class="values"><span class="label">Wi‑Fi</span><span class="value" id="wifi">—</span><span class="label">RSSI</span><span class="value" id="rssi">—</span><span class="label">IP adresa</span><span class="value" id="ip">—</span></div></section>
    <section class="card"><h2>Paměť</h2><div class="values"><span class="label">Interní volná</span><span class="value" id="internalFree">—</span><span class="label">Největší blok</span><span class="value" id="internalLargest">—</span><span class="label">Minimum od startu</span><span class="value" id="internalMinimum">—</span><span class="label">PSRAM volná</span><span class="value" id="psramFree">—</span><span class="label">Největší blok</span><span class="value" id="psramLargest">—</span><span class="label">Minimum od startu</span><span class="value" id="psramMinimum">—</span><span class="label">Zásobník loop</span><span class="value" id="loopStack">—</span><span class="label">Zásobník dat</span><span class="value" id="homeAssistantStack">—</span></div></section>
    <section class="card wide"><h2>Meteoradar ČHMÚ</h2><div class="values"><span class="label">Lokalita</span><span class="value" id="radarLocation">—</span><span class="label">GPS souřadnice</span><span class="value" id="radarGps">—</span><span class="label">Dostupnost</span><span class="value" id="radarAvailable">—</span><span class="label">Rozsah</span><span class="value" id="radarRange">—</span><span class="label">Připravené snímky</span><span class="value" id="radarFrames">—</span><span class="label">Časy snímků</span><span class="value" id="radarTimes">—</span><span class="label">Poslední úspěšná aktualizace</span><span class="value" id="radarLastRefresh">—</span><span class="label">Další kontrola</span><span class="value" id="radarNextRefresh">—</span><span class="label">Radarová obrazovka</span><span class="value" id="radarActive">—</span><span class="label">Stav</span><span class="value" id="radarState">—</span><span class="label">Poslední odpověď ČHMÚ</span><span class="value" id="radarHttp">—</span></div></section>
    <section class="card wide"><h2>Open-Meteo a TMEP.cz</h2><div class="values"><span class="label">Open-Meteo</span><span class="value" id="openMeteoResult">—</span><span class="label">Detail Open-Meteo</span><span class="value" id="openMeteoDetail">—</span><span class="label">TMEP.cz</span><span class="value" id="tmepResult">—</span><span class="label">Detail TMEP.cz</span><span class="value" id="tmepDetail">—</span></div></section>
    <section class="card wide"><h2>Home Assistant a DEN/NOC</h2><div class="values"><span class="label">Poslední výsledek</span><span class="value" id="haResult">—</span><span class="label">Úspěšné / chybné požadavky</span><span class="value" id="haCounts">—</span><span class="label">Poslední dokončení</span><span class="value" id="haFinished">—</span><span class="label">Detail</span><span class="value" id="haDetail">—</span><span class="label">Stav SUN</span><span class="value" id="sunState">—</span><span class="label">Stav světla nebo skupiny</span><span class="value" id="lightState">—</span><span class="label">Aktuální režim displeje</span><span class="value" id="displayMode">—</span></div></section>
  </div>
  <div class="notice">Tato diagnostika je pouze pro čtení. Nastavení zařízení ani uložené hodnoty nemění.</div>
  <div class="footer">Údaje se automaticky obnovují každých 5 sekund. <span class="pulse" id="lastRefresh">Čekám na první načtení…</span></div>
</main>
<script src="/ui-language.js"></script>
<script>
const $=id=>document.getElementById(id);
function renderStack(id,value){const free=Number(value);const element=$(id);if(!Number.isFinite(free)||free<=0){element.textContent="—";element.className="value";return}element.textContent=bytes(free);element.className="value "+(free<3072?"warn":"ok")}
const bytes=value=>{const number=Number(value)||0;if(number>=1048576)return(number/1048576).toFixed(1)+" MB";if(number>=1024)return Math.round(number/1024)+" kB";return number+" B"};
const duration=value=>{let seconds=Math.floor((Number(value)||0)/1000);const days=Math.floor(seconds/86400);seconds%=86400;const hours=Math.floor(seconds/3600);seconds%=3600;const minutes=Math.floor(seconds/60);return(days?days+" d ":"")+(hours?hours+" h ":"")+minutes+" min"};
const ago=(uptime,finished)=>{if(!finished)return"Dosud neproběhlo";const seconds=Math.max(0,Math.floor((uptime-finished)/1000));return seconds<60?seconds+" s zpět":Math.floor(seconds/60)+" min zpět"};
const shortDuration=value=>{const seconds=Math.max(0,Math.floor((Number(value)||0)/1000));if(seconds<60)return seconds+" s";const minutes=Math.floor(seconds/60);if(minutes<60)return minutes+" min";const hours=Math.floor(minutes/60);return hours+" h "+minutes%60+" min"};
const resetReasons={0:"Neznámý",1:"Zapnutí napájení",2:"Externí reset",3:"Softwarový restart",4:"Pád systému",5:"Watchdog přerušení",6:"Watchdog úlohy",7:"Jiný watchdog",8:"Probuzení z deep sleep",9:"Pokles napájení",10:"Reset SDIO",11:"Reset USB",12:"Reset JTAG",13:"Chyba eFuse",14:"Výpadek napájení",15:"Zablokování CPU"};
function render(data){$("firmwareVersion").textContent=data.firmwareVersion||"—";$("firmwareState").textContent=data.firmwareMessage||data.firmwareState||"—";$("uptime").textContent=duration(data.uptimeMs);$("chip").textContent=(data.chipModel||"—")+(data.chipRevision!=null?" rev. "+data.chipRevision:"");$("cpu").textContent=(data.cpuFrequencyMHz||0)+" MHz";const displayClock=Number(data.displayPixelClockHz)||0;$("displayClock").textContent=displayClock?(displayClock/1000000).toLocaleString("cs-CZ")+" MHz":"—";$("flash").textContent=bytes(data.flashSize);$("psram").textContent=bytes(data.psramSize);$("wifi").textContent=data.wifiConnected?"Připojeno":"Odpojeno";$("wifi").className="value "+(data.wifiConnected?"ok":"error");$("rssi").textContent=data.wifiConnected?data.wifiRssi+" dBm":"—";$("ip").textContent=data.ipAddress||"—";const memory=data.currentMemory||{};$("internalFree").textContent=bytes(memory.internalFree);$("internalLargest").textContent=bytes(memory.internalLargest);$("psramFree").textContent=bytes(memory.psramFree);$("psramLargest").textContent=bytes(memory.psramLargest);const ha=data.homeAssistantRuntime||{};$("haResult").textContent=ha.lastResult===200?"V pořádku":ha.lastResult?"Chyba "+ha.lastResult:"Dosud neproběhlo";$("haResult").className="value "+(ha.lastResult===200?"ok":ha.lastResult?"error":"");$("haCounts").textContent=(ha.successes||0)+" / "+(ha.failures||0);$("haFinished").textContent=ago(data.uptimeMs,ha.lastFinishedAt);$("haDetail").textContent=ha.detail||"—";$("lastRefresh").textContent="Aktualizováno "+new Date().toLocaleTimeString("cs-CZ");}
function renderExtended(data){$("resetReason").textContent=resetReasons[data.resetReason]||"Kód "+data.resetReason;const minimum=data.minimumMemory||{};$("internalMinimum").textContent=bytes(minimum.internalFree);$("psramMinimum").textContent=bytes(minimum.psramFree);renderStack("loopStack",data.taskStacks?.loop);renderStack("homeAssistantStack",data.taskStacks?.homeAssistant);const radar=data.chmiRadar||{};$("radarLocation").textContent=radar.location||"—";const latitude=Number(radar.latitude),longitude=Number(radar.longitude);$("radarGps").textContent=Number.isFinite(latitude)&&Number.isFinite(longitude)?latitude.toFixed(5)+", "+longitude.toFixed(5):"—";$("radarAvailable").textContent=radar.available?"Dostupný pro ČR":"Vypnutý mimo ČR";$("radarAvailable").className="value "+(radar.available?"ok":"warn");$("radarRange").textContent=Number(radar.radiusKm)===0?"Celá ČR":radar.radiusKm+" km";$("radarFrames").textContent=(radar.preparedFrameCount||0)+" / "+(radar.requestedFrameCount||0);$("radarTimes").textContent=radar.oldestFrameTime&&radar.newestFrameTime?radar.oldestFrameTime+"–"+radar.newestFrameTime:"Dosud nejsou připravené";$("radarLastRefresh").textContent=radar.lastSuccessfulRefreshAvailable?shortDuration(radar.lastSuccessfulRefreshAgeMs)+" zpět":"Dosud neproběhla";$("radarNextRefresh").textContent=!radar.available?"Vypnuto":radar.nextRefreshInMs?"za "+shortDuration(radar.nextRefreshInMs):radar.loading?"Právě probíhá":!radar.active?"Při příštím otevření":"Čeká na naplánování";$("radarActive").textContent=radar.active?"Zobrazená":"Skrytá";$("radarActive").className="value "+(radar.active?"ok":"");$("radarState").textContent=!radar.available?"Nedostupný pro zvolenou zemi":radar.loading?"Načítání":radar.preparationInProgress?"Příprava animace":radar.message||(radar.ready?"Připraveno":"Čeká na první otevření");$("radarHttp").textContent=radar.lastHttpStatus?"HTTP "+radar.lastHttpStatus:"Dosud bez požadavku";}
function renderDayNight(data){$("firmwareState").textContent=data.firmwareState==="idle"?"Připraveno":data.firmwareState||"—";$("sunState").textContent=data.sunStateAvailable?(data.sunIsDay?"Nad horizontem / den":"Pod horizontem / noc"):"Není načten";$("lightState").textContent=data.dayNightLightStateAvailable?(data.dayNightLightOn?"ON":"OFF"):"Není načteno";$("displayMode").textContent=data.nightMode?"Noční":"Denní";$("displayMode").className="value "+(data.nightMode?"":"ok")}
function renderExternal(data){const open=data.openMeteoRuntime||{};const tmep=data.tmepRuntime||{};const setResult=(id,diagnostic)=>{const element=$(id);element.textContent=!diagnostic.attempts?"Dosud neproběhlo":diagnostic.lastSuccess?"V pořádku":diagnostic.lastResult?"Chyba "+diagnostic.lastResult:"Chyba";element.className="value "+(!diagnostic.attempts?"":diagnostic.lastSuccess?"ok":"error")};setResult("openMeteoResult",open);setResult("tmepResult",tmep);$("openMeteoDetail").textContent=open.detail||"—";$("tmepDetail").textContent=tmep.detail||"—"}
async function refresh(){try{const response=await fetch("/api/status",{cache:"no-store"});if(!response.ok)throw new Error("HTTP "+response.status);const data=await response.json();window.clockUiSetLanguage?.(data.language);render(data);renderExtended(data);renderDayNight(data);renderExternal(data);$("connectionState").textContent="Zařízení je připojeno";$("connectionState").className="state"}catch(error){$("connectionState").textContent="Zařízení neodpovídá";$("connectionState").className="state error";$("lastRefresh").textContent=error.message}}
refresh();setInterval(refresh,5000);
</script>
</body>
</html>)HTML";
